tf.data

tf.data.Dataset
集合
每个元素存放一个或多个tf.Tensor对象


In [30]:
import tensorflow as tf 
import numpy as np

In [31]:
dataset = tf.data.Dataset.from_tensor_slices([1,2,3,4,5,6,7])

In [32]:
dataset

<TensorSliceDataset shapes: (), types: tf.int32>

In [33]:
for ele in dataset:
    print(ele)

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(5, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(7, shape=(), dtype=int32)


In [34]:
for ele in dataset:
    # 将Tensor准换为nump类型
    print(ele.numpy())

1
2
3
4
5
6
7


In [35]:
# 元素为二维数据
dataset = tf.data.Dataset.from_tensor_slices([[1,2],[3,4],[5,6]])

In [36]:
dataset

<TensorSliceDataset shapes: (2,), types: tf.int32>

In [37]:
for ele in dataset:
    # 将Tensor准换为nump类型
    print(ele.numpy())

[1 2]
[3 4]
[5 6]


In [38]:
# 用字典初始化
dataset_dic = tf.data.Dataset.from_tensor_slices(
    {
        'a':[1,2,3,4],
        'b':[6,7,8,9],
        'c':[12,13,14,15]
    }
)

In [39]:
dataset_dic

<TensorSliceDataset shapes: {a: (), b: (), c: ()}, types: {a: tf.int32, b: tf.int32, c: tf.int32}>

In [40]:
for ele in dataset_dic:
    print(ele)

{'a': <tf.Tensor: shape=(), dtype=int32, numpy=1>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=6>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=12>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=2>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=7>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=13>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=3>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=8>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=14>}
{'a': <tf.Tensor: shape=(), dtype=int32, numpy=4>, 'b': <tf.Tensor: shape=(), dtype=int32, numpy=9>, 'c': <tf.Tensor: shape=(), dtype=int32, numpy=15>}


In [41]:
# 用numpy创建
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6]))

In [42]:
# take方法
for ele in dataset.take(4):
    print(ele.numpy())

1
2
3
4


In [43]:
# 乱序（buffer_size 多大范围内进行乱序，一般用全部）
dataset = dataset.shuffle(6)
# 重复（count 多少次）
dataset = dataset.repeat(count=3)
# 每次输出几个元素（和内存相关）
dataset = dataset.batch(3)

In [44]:
for ele in dataset:
    print(ele.numpy())

[2 6 3]
[1 5 4]
[5 1 3]
[6 2 4]
[6 1 3]
[2 4 5]


In [45]:
dataset = tf.data.Dataset.from_tensor_slices(np.array([1,2,3,4,5,6]))

In [46]:
# map，对每个元素做映射
dataset = dataset.map(tf.square)

In [47]:
for ele in dataset:
    print(ele.numpy())

1
4
9
16
25
36
